# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab3f73cec810fc393c460b3bcd5c10819df38efbb26dde613bdd9ff758abbf0fa8d467ba9faa1c05506cb95eda7decfd2e776287711b27ba2c0ee0d9a2ff94bd

test:
  secret_key_base: c6c2c7a5bf7b3495117cfd9c467e9398a972568329cbfdb7c47143afdaf44a56ea7b5ec02d891d56ac9ef4f1047d139225d69964003153d49cb1fcb8b1c80e71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
